### ISSUE TITLE
warning: 'esp_wifi_config_espnow_rate' is deprecated (AEGHB-556)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-now#111]
with:
```
  espressif/esp-now:
    component_hash: 7355037518944af5d0ea20fe48aa0a8cf82081599b6fbd83f086ee8b39df87c1
    source:
      service_url: https://api.components.espressif.com/
      type: service
    version: 2.4.0
```

and 

```
  idf:
    component_hash: null
    source:
      type: idf
    version: 5.1.2
```

i get: 

```
/home/franz/git/hr/LOGIBUS_integration_HutschienenmopedXL/Application/managed_components/espressif__esp-now/src/debug/src/commands/cmd_iperf.c: In function 'espnow_config_func':
/home/franz/git/hr/LOGIBUS_integration_HutschienenmopedXL/Application/managed_components/espressif__esp-now/src/debug/src/commands/cmd_iperf.c:113:9: warning: 'esp_wifi_config_espnow_rate' is deprecated: This API can be only used when rate is non-HE rate,                                 please use esp_now_set_peer_rate_config if you want full support of the rate. [-Wdeprecated-declarations]
  113 |         ESP_ERROR_CHECK(esp_wifi_config_espnow_rate(ESP_IF_WIFI_STA, espnow_config_args.rate->ival[0]));
      |         ^~~~~~~~~~~~~~~
In file included from /home/franz/git/hr/LOGIBUS_integration_HutschienenmopedXL/Application/managed_components/espressif__esp-now/src/espnow/include/espnow.h:17,
                 from /home/franz/git/hr/LOGIBUS_integration_HutschienenmopedXL/Application/managed_components/espressif__esp-now/src/debug/src/commands/cmd_iperf.c:28:
/home/franz/esp-idf-v5.1.2/components/esp_wifi/include/esp_now.h:267:11: note: declared here
  267 | esp_err_t esp_wifi_config_espnow_rate(wifi_interface_t ifx, wifi_phy_rate_t rate)
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
